added more article.py testing
ThreadNews/threadnews-backend pull request #56
Opened 2021-06-04 20:00 UTC by sfparrett

2021-06-04 20:01 UTC, Jack-kelly-22 approved these changes

2021-06-04 20:02 UTC, akwong189 approved these changes
Tests look good to go

2021-06-06 00:23 UTC, akwong189 approved these changes

2021-06-06 21:20 UTC, akwong189 requested changes

2021-06-06 21:20 UTC, akwong189 commented on endpoints/frontend.py
> -from utils.Podcast import SpotifyPodcast
this causes an error as utils.podcast has no SpotifyPodcast, only Podcast

2021-06-07 07:07 UTC, akwong189 approved these changes
Fixes made, should be good to go

2021-06-07 07:12 UTC, merged